{
  "swagger": "2.0",
  "info": {
    "description": "这是<a target='_blank' href='https://github.com/DavidNineRoc/monday-shop'>monday-shop</a>的 api 文档, 在这里你可以看到所有可用的 API!!! 文档中响应预期返回是`Example Value`, 需要查看字段含义请查看`Model`切换查看\n如果在文档测试需登录的接口,请点击文档右边的小锁头,使用登录的token进行验证身份\n全局成功状态码: `200, 201(创建成功) 204(删除成功)`",
    "version": "1.0.0",
    "title": "API 文档",
    "contact": {
      "email": "1033404553@qq.com"
    }
  },
  "host": "localhost:8000",
  "basePath": "/api/v1",
  "tags": [
    {
      "name": "Auth",
      "description": "登录授权验证相关的接口"
    },
    {
      "name": "Product",
      "description": "商品相关的接口"
    },
    {
      "name": "OWN",
      "description": "个人相关的接口"
    }
  ],
  "parameters": {
    "limit": {
      "name": "limit",
      "in": "query",
      "default": "10",
      "description": "分页参数的取的条数",
      "type": "integer"
    },
    "page": {
      "name": "page",
      "in": "query",
      "default": "1",
      "type": "integer",
      "description": "分页参数的页码"
    }
  },
  "schemes": [
    "http"
  ],
  "paths": {
    "/categories": {
      "get": {
        "summary": "获取商品的拥有分类",
        "description": "此接口暂时不支持排序,因为后台设置有排序字段",
        "tags": [
          "Product"
        ],
        "security": [
          {
            "token": [

            ]
          }
        ],
        "parameters": [
          {
            "$ref": "#/parameters/limit"
          },
          {
            "$ref": "#/parameters/page"
          },
          {
            "name": "name",
            "description": "分类的名字,模糊查询",
            "type": "string",
            "required": false,
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "schema": {
              "properties": {
                "code": {
                  "type": "integer",
                  "description": "根据此状态码判断返回的数据, 200 成功, 201 创建成功, 204 修改成功, 其他均为失败"
                },
                "msg": {
                  "type": "string",
                  "description": "此次Http请求描述信息, 如果 code 为非成功, 那么可显示此条错误消息"
                },
                "data": {
                  "type": "array",
                  "items": {
                    "$ref": "#/definitions/Category"
                  }
                },
                "count": {
                  "type": "string",
                  "default": "数据的总条数"
                }
              },
              "example": {
                "code": 200,
                "msg": "success",
                "data": [
                  {
                    "id": 1,
                    "name": "个人护理",
                    "description": "Consequatur nostrum blanditiis dolor alias et.",
                    "icon": "fa-pencil",
                    "thumb": "https://lorempixel.com/110/110/?47191"
                  },
                  {
                    "id": 2,
                    "name": "运动户外",
                    "description": "Eos autem repellat et maiores autem iste labore.",
                    "icon": "",
                    "thumb": "https://lorempixel.com/110/110/?20394"
                  },
                  {
                    "id": 3,
                    "name": "电脑办公",
                    "description": "Dolor repudiandae sunt sed inventore quaerat.",
                    "icon": "",
                    "thumb": "https://lorempixel.com/110/110/?49939"
                  },
                  {
                    "id": 4,
                    "name": "珠宝饰品",
                    "description": "Deleniti voluptates neque consequatur fugiat.",
                    "icon": "",
                    "thumb": "https://lorempixel.com/110/110/?39035"
                  },
                  {
                    "id": 5,
                    "name": "手机数码",
                    "description": "Et dolore eos reiciendis.",
                    "icon": "",
                    "thumb": "https://lorempixel.com/110/110/?10489"
                  },
                  {
                    "id": 6,
                    "name": "美食零食",
                    "description": "Iusto corporis et nihil et cupiditate.",
                    "icon": "",
                    "thumb": "https://lorempixel.com/110/110/?54091"
                  },
                  {
                    "id": 7,
                    "name": "鲜花园艺",
                    "description": "Illum quod vel nam facere in voluptates dolore.",
                    "icon": "",
                    "thumb": "https://lorempixel.com/110/110/?13912"
                  },
                  {
                    "id": 8,
                    "name": "品质汽车",
                    "description": "Ipsam impedit aut eos corporis et velit.",
                    "icon": "",
                    "thumb": "https://lorempixel.com/110/110/?93450"
                  }
                ],
                "count": 8
              }
            }
          }
        }
      }
    },
    "/tokens": {
      "post": {
        "summary": "登录接口",
        "description": "登录账号信息用户换取 token",
        "tags": [
          "Auth"
        ],
        "security": [
          {
            "token": []
          }
        ],
        "consumes": [
          "multipart/form-data"
        ],
        "parameters": [
          {
            "name": "username",
            "description": "用户名 {第三方登录的用户请进入个人中心设置用户名再使用此方式登录}",
            "type": "string",
            "in": "formData",
            "required": true
          },
          {
            "name": "password",
            "description": "密码",
            "type": "string",
            "in": "formData",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "响应中有 token 和 prefix, 如果之后请求放在请求头之中, 格式必须是(prefix token)",
            "schema": {
              "properties": {
                "code": {
                  "type": "integer",
                  "description": "根据此状态码判断返回的数据, 200 成功, 201 创建成功, 204 修改成功, 其他均为失败"
                },
                "msg": {
                  "type": "string",
                  "description": "此次Http请求描述信息, 如果 code 为非成功, 那么可显示此条错误消息"
                },
                "data": {
                  "type": "object",
                  "description": "所有数据都在data中",
                  "properties": {
                    "prefix": {
                      "type": "string",
                      "description": "jwt 前缀"
                    },
                    "token": {
                      "type": "string",
                      "description": "jwt 的授权验证信息"
                    },
                    "me": {
                      "$ref": "#/definitions/Me",
                      "description": "用户的个人信息, 也可 me 请求接口获取, 建议保存起来减少后续调用接口使用"
                    }
                  }
                }
              },
              "example": {
                "code": 200,
                "msg": "登录成功",
                "data": {
                  "prefix": "Bearer",
                  "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9sb2NhbGhvc3Q6ODA4MFwvYXBpXC92MVwvdG9rZW5zIiwiaWF0IjoxNTU3OTA2NjYwLCJleHAiOjE1NTc5MTAyNjAsIm5iZiI6MTU1NzkwNjY2MCwianRpIjoiZnBUdGozVWJmUVg2TWZlQiIsInN1YiI6NiwicHJ2IjoiMjNiZDVjODk0OWY2MDBhZGIzOWU3MDFjNDAwODcyZGI3YTU5NzZmNyJ9.kHN2pg04JuLwKSvCbcVBN3XdO05erOG3uVs9EfBJajM",
                  "me": {
                    "username": "david",
                    "sex": 1,
                    "email": "",
                    "avatar": "https://avatars0.githubusercontent.com/u/28035971?v=4",
                    "github_name": "大卫",
                    "qq_name": "",
                    "weibo_name": "",
                    "score_all": 121845,
                    "score_now": 121845,
                    "login_days": 1,
                    "last_login_date": "2019-03-22",
                    "is_init_name": false,
                    "is_init_email": true,
                    "is_init_password": false
                  }
                }
              }
            }
          }
        }
      },
      "delete": {
        "summary": "注销",
        "description": "退出系统登录",
        "tags": [
          "Auth"
        ],
        "security": [
          {
            "token": []
          }
        ],
        "consumes": [
          "multipart/form-data"
        ],
        "responses": {
          "200": {
            "description": "success",
            "schema": {
              "properties": {
                "code": {
                  "type": "integer",
                  "description": "根据此状态码判断返回的数据, 200 成功, 201 创建成功, 204 修改成功, 其他均为失败"
                },
                "msg": {
                  "type": "string",
                  "description": "此次Http请求描述信息, 如果 code 为非成功, 那么可显示此条错误消息"
                },
                "data": {
                  "type": "array",
                  "description": "默认无数据"
                }
              },
              "example": {
                "code": 204,
                "msg": "注销成功",
                "data": []
              }
            }
          }
        }
      }
    },
    "/users": {
      "post": {
        "summary": "注册接口",
        "description": "注册用户并得到 token",
        "tags": [
          "Auth"
        ],
        "security": [
          {
            "token": []
          }
        ],
        "consumes": [
          "multipart/form-data"
        ],
        "parameters": [
          {
            "name": "username",
            "description": "用户名",
            "type": "string",
            "in": "formData",
            "required": true
          },
          {
            "name": "password",
            "description": "密码",
            "type": "string",
            "in": "formData",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "响应中有 token 和 prefix, 如果之后请求放在请求头之中, 格式必须是(prefix token)",
            "schema": {
              "properties": {
                "code": {
                  "type": "integer",
                  "description": "根据此状态码判断返回的数据, 200 成功, 201 创建成功, 204 修改成功, 其他均为失败"
                },
                "msg": {
                  "type": "string",
                  "description": "此次Http请求描述信息, 如果 code 为非成功, 那么可显示此条错误消息"
                },
                "data": {
                  "type": "object",
                  "description": "所有数据都在data中",
                  "properties": {
                    "prefix": {
                      "type": "string",
                      "description": "jwt 前缀"
                    },
                    "token": {
                      "type": "string",
                      "description": "jwt 的授权验证信息"
                    },
                    "me": {
                      "$ref": "#/definitions/Me",
                      "description": "用户的个人信息, 也可 me 请求接口获取, 建议保存起来减少后续调用接口使用"
                    }
                  }
                }
              },
              "example": {
                "code": 201,
                "msg": "注册成功",
                "data": {
                  "prefix": "Bearer",
                  "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9sb2NhbGhvc3Q6ODA4MFwvYXBpXC92MVwvdG9rZW5zIiwiaWF0IjoxNTU3OTA2NjYwLCJleHAiOjE1NTc5MTAyNjAsIm5iZiI6MTU1NzkwNjY2MCwianRpIjoiZnBUdGozVWJmUVg2TWZlQiIsInN1YiI6NiwicHJ2IjoiMjNiZDVjODk0OWY2MDBhZGIzOWU3MDFjNDAwODcyZGI3YTU5NzZmNyJ9.kHN2pg04JuLwKSvCbcVBN3XdO05erOG3uVs9EfBJajM",
                  "me": {
                    "username": "david",
                    "sex": 1,
                    "email": "",
                    "avatar": "https://avatars0.githubusercontent.com/u/28035971?v=4",
                    "github_name": "大卫",
                    "qq_name": "",
                    "weibo_name": "",
                    "score_all": 0,
                    "score_now": 0,
                    "login_days": 1,
                    "last_login_date": "2019-03-22",
                    "is_init_name": false,
                    "is_init_email": true,
                    "is_init_password": false
                  }
                }
              }
            }
          }
        }
      }
    },
    "/own/me": {
      "get": {
        "summary": "个人信息",
        "description": "获取个人信息(和登录获取到的信息一致)",
        "tags": [
          "OWN"
        ],
        "security": [
          {
            "token": []
          }
        ],
        "consumes": [
          "multipart/form-data"
        ],
        "responses": {
          "200": {
            "description": "success",
            "schema": {
              "properties": {
                "code": {
                  "type": "integer",
                  "description": "根据此状态码判断返回的数据, 200 成功, 201 创建成功, 204 修改成功, 其他均为失败"
                },
                "msg": {
                  "type": "string",
                  "description": "此次Http请求描述信息, 如果 code 为非成功, 那么可显示此条错误消息"
                },
                "data": {
                  "$ref": "#/definitions/Me",
                  "description": "用户的个人信息, 也可 me 请求接口获取, 建议保存起来减少后续调用接口使用"
                }
              },
              "example": {
                "code": 200,
                "msg": "success",
                "data": {
                  "username": "david",
                  "sex": 1,
                  "email": "",
                  "avatar": "https://avatars0.githubusercontent.com/u/28035971?v=4",
                  "github_name": "david",
                  "qq_name": "",
                  "weibo_name": "",
                  "score_all": 121855,
                  "score_now": 121855,
                  "login_days": 1,
                  "last_login_date": "2019-05-15",
                  "is_init_name": false,
                  "is_init_email": true,
                  "is_init_password": false
                }
              }
            }
          }
        }
      }
    },
    "/own/score_logs": {
      "get": {
        "summary": "积分记录",
        "description": "用户操作积分获取记录",
        "tags": [
          "OWN"
        ],
        "security": [
          {
            "token": []
          }
        ],
        "consumes": [
          "multipart/form-data"
        ],
        "parameters": [
          {
            "$ref": "#/parameters/limit"
          },
          {
            "$ref": "#/parameters/page"
          }
        ],
        "responses": {
          "200": {
            "description": "success",
            "schema": {
              "properties": {
                "code": {
                  "type": "integer",
                  "description": "根据此状态码判断返回的数据, 200 成功, 201 创建成功, 204 修改成功, 其他均为失败"
                },
                "msg": {
                  "type": "string",
                  "description": "此次Http请求描述信息, 如果 code 为非成功, 那么可显示此条错误消息"
                },
                "data": {
                  "type": "array",
                  "items": {
                    "$ref": "#/definitions/ScoreLog"
                  }
                },
                "count": {
                  "type": "string",
                  "default": "数据的总条数"
                }
              },
              "example": {
                "code": 200,
                "msg": "success",
                "data": [
                  {
                    "id": 4,
                    "description": "2019-05-15 16:59:29进行了登录。",
                    "score": 5,
                    "created_at": "2019-05-15 16:59:29"
                  }
                ],
                "count": 1
              }
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Category": {
      "type": "object",
      "properties": {
        "id": {
          "type": "integer",
          "default": "记录主键"
        },
        "name": {
          "type": "string",
          "description": "分类的名字"
        },
        "description": {
          "type": "string",
          "description": "分类的描述"
        },
        "icon": {
          "type": "string",
          "description": "分类的图标"
        },
        "thumb": {
          "type": "string",
          "description": "分类的缩略图"
        }
      }
    },
    "ScoreLog": {
      "type": "object",
      "properties": {
        "id": {
          "type": "integer",
          "default": "记录主键"
        },
        "description": {
          "type": "string",
          "description": "积分的获取说明"
        },
        "score": {
          "type": "integer",
          "description": "积分的获取值"
        },
        "created_at": {
          "type": "string",
          "description": "积分的获取时间"
        }
      }
    },
    "Me": {
      "type": "object",
      "properties": {
        "username": {
          "type": "string",
          "description": "用户登录名"
        },
        "sex": {
          "type": "integer",
          "enum": [
            1, 2
          ],
          "description": "用户性别, 1 为男, 2 为女"
        },
        "email": {
          "type": "string",
          "description": "用户的邮箱"
        },
        "avatar": {
          "type": "string",
          "description": "用户的头像"
        },
        "github_name": {
          "type": "string",
          "description": "github 第三方昵称"
        },
        "qq_name": {
          "type": "string",
          "description": "qq 第三方昵称"
        },
        "weibo_name": {
          "type": "string",
          "description": "weibo 第三方昵称"
        },
        "score_all": {
          "type": "integer",
          "description": "用户的总积分"
        },
        "score_now": {
          "type": "integer",
          "description": "用户的剩余积分"
        },
        "login_days": {
          "type": "integer",
          "description": "用户连续登录天数"
        },
        "last_login_date": {
          "type": "string",
          "description": "上一次登录的日期"
        },
        "is_init_name": {
          "type": "boolean",
          "description": "是否是初始用户名, 如果是第三方登录的那么返回 true, 代表可以设置用户名 username"
        },
        "is_init_email": {
          "type": "boolean",
          "description": "是否是初始邮箱, 如果是第三方登录的那么返回 true, 代表可以设置用户名 email"
        },
        "is_init_password": {
          "type": "boolean",
          "description": "是否是初始密码, 如果是第三方登录的那么返回 true, 代表可以不用输入旧密码也可以设置新密码"
        }
      }
    }
  },
  "securityDefinitions": {
    "token": {
      "type": "apiKey",
      "name": "Authorization",
      "in": "header",
      "description": "使用登录返回的 前缀+token, 或者刷新返回的值. 实例值:`Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9sb2NhbGhvc3Q6ODAwMFwvYXBpXC92MVwvdG9rZW5zIiwiaWF0IjoxNTU3ODI1NjcyLCJleHAiOjE1NTc4MjkyNzIsIm5iZiI6MTU1NzgyNTY3MiwianRpIjoidnFySVlZS0p2UU1qSnhRNCIsInN1YiI6NiwicHJ2IjoiMjNiZDVjODk0OWY2MDBhZGIzOWU3MDFjNDAwODcyZGI3YTU5NzZmNyJ9.AOlUsM51oDz4yoAFsXzz5n1E65Bo17pKUnDg_Nh-DnY`"
    }
  }
}
